// example/tailwind-system-example-vue3/src/components/Box.vue
<template>
  <component :is="tag" :class="classNames">
    <slot />
  </component>
</template>

<script>
import { ref, computed } from "vue";
import { propsToClasses, vuePropTypes } from 'tailwind-system'
const classNameProps = vuePropTypes.box
export default {
  name: 'Box',
  props: {
    tag: { type: String, default: 'div' },
    ...classNameProps
  },
  setup(props){
    const mapKeys = {
      'text-align': 'text',
      display: ''
    }
    const classNames = computed( () => propsToClasses(props, classNameProps, { mapKeys }))
    return {
      tag : props.tag || 'div',
      classNames
    }
  }
}
</script>

// example/tailwind-system-example-react/src/Box.js
import React from 'react'
import { propsToClasses, reactPropTypes } from 'tailwind-system'

const propTypes = {
  ...reactPropTypes.box,
}

const Box = ({children, ...props}) => {
  const classNames = propsToClasses(props, propTypes)
  return (
    <div className={classNames}>
      {children}
    </div>
  );
}

Box.propTypes = propTypes

export default Box
